"""Repository interfaces.

This is the part of the repository pattern that actually earns its keep. Services depend on
these ``Protocol`` types, not on the SQLAlchemy-backed classes, so a unit test can pass a
dictionary-backed fake and exercise real business logic with no database at all.

``Protocol`` gives *structural* typing: a class satisfies one of these by having methods with
matching signatures. Neither the real repository nor a test fake needs to inherit from
anything — which means the fakes stay trivially small, and mypy still verifies they match the
contract the service depends on.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Protocol

from app.models.career_goal import CareerGoal
from app.models.email_verification_token import EmailVerificationToken
from app.models.job import Job
from app.models.password_reset_token import PasswordResetToken
from app.models.refresh_token import RefreshToken
from app.models.resume import Resume
from app.models.skill import Skill
from app.models.user import User
from app.models.user_skill import SkillStatus, UserSkill
from app.repositories.candidate import CandidateProfile
from app.services.skill_graph import GraphSkill
from app.services.skill_matching import VocabularyEntry


class UnitOfWork(Protocol):
    """The transaction boundary, narrowed to what services are allowed to do.

    ``AsyncSession`` satisfies this structurally, so the real implementation is just the
    session. Services get ``commit`` and ``flush`` and nothing else — no ``execute``, so a
    service cannot quietly bypass the repositories and run its own SQL.
    """

    async def commit(self) -> None: ...
    async def flush(self) -> None: ...


class UserRepositoryProtocol(Protocol):
    async def get(self, entity_id: uuid.UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def email_exists(self, email: str) -> bool: ...
    async def get_by_google_sub(self, google_sub: str) -> User | None: ...
    def add(self, entity: User) -> User: ...


class RefreshTokenRepositoryProtocol(Protocol):
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke_family(self, family_id: uuid.UUID, revoked_at: datetime) -> int: ...
    async def revoke_all_for_user(self, user_id: uuid.UUID, revoked_at: datetime) -> int: ...
    def add(self, entity: RefreshToken) -> RefreshToken: ...


class EmailVerificationTokenRepositoryProtocol(Protocol):
    async def get_by_hash(self, token_hash: str) -> EmailVerificationToken | None: ...
    async def invalidate_active_for_user(self, user_id: uuid.UUID, used_at: datetime) -> int: ...
    def add(self, entity: EmailVerificationToken) -> EmailVerificationToken: ...


class PasswordResetTokenRepositoryProtocol(Protocol):
    async def get_by_hash(self, token_hash: str) -> PasswordResetToken | None: ...
    async def invalidate_active_for_user(self, user_id: uuid.UUID, used_at: datetime) -> int: ...
    def add(self, entity: PasswordResetToken) -> PasswordResetToken: ...


class ResumeRepositoryProtocol(Protocol):
    async def get_for_user(self, resume_id: uuid.UUID, user_id: uuid.UUID) -> Resume | None: ...
    async def get_with_text(self, resume_id: uuid.UUID, user_id: uuid.UUID) -> Resume | None: ...
    async def list_for_user(self, user_id: uuid.UUID, *, limit: int = 50) -> list[Resume]: ...
    async def count_pending_for_user(self, user_id: uuid.UUID) -> int: ...
    async def latest_embedded_for_user(self, user_id: uuid.UUID) -> Resume | None: ...
    def add(self, entity: Resume) -> Resume: ...


class JobRepositoryProtocol(Protocol):
    async def get_visible(self, job_id: uuid.UUID, user_id: uuid.UUID) -> Job | None: ...
    async def get_owned(self, job_id: uuid.UUID, user_id: uuid.UUID) -> Job | None: ...
    async def list_visible(self, user_id: uuid.UUID, *, limit: int = 50) -> list[Job]: ...
    async def list_public(self, *, limit: int = 50) -> list[Job]: ...
    async def reload(self, job_id: uuid.UUID) -> Job | None: ...
    async def replace_skills(
        self, job_id: uuid.UUID, entries: list[tuple[uuid.UUID, int]]
    ) -> None: ...
    def add(self, entity: Job) -> Job: ...
    async def delete(self, entity: Job) -> None: ...


class CareerGoalRepositoryProtocol(Protocol):
    async def get_active_for_user(self, user_id: uuid.UUID) -> CareerGoal | None: ...
    async def get_owned(self, goal_id: uuid.UUID, user_id: uuid.UUID) -> CareerGoal | None: ...
    async def list_achieved_for_user(
        self, user_id: uuid.UUID, *, limit: int = 20
    ) -> list[CareerGoal]: ...
    def add(self, entity: CareerGoal) -> CareerGoal: ...
    async def delete(self, entity: CareerGoal) -> None: ...


class CandidateRepositoryProtocol(Protocol):
    async def load_candidate_profiles(
        self, *, statuses: tuple[SkillStatus, ...], limit: int = 50
    ) -> list[CandidateProfile]: ...


class SkillRepositoryProtocol(Protocol):
    async def get(self, entity_id: uuid.UUID) -> Skill | None: ...
    async def list_all(self) -> list[Skill]: ...
    async def get_by_slug(self, slug: str) -> Skill | None: ...
    async def load_vocabulary(self) -> list[VocabularyEntry]: ...
    async def load_graph_skills(self) -> list[GraphSkill]: ...
    async def load_edges(self) -> list[tuple[uuid.UUID, uuid.UUID]]: ...


class UserSkillRepositoryProtocol(Protocol):
    async def get(self, user_id: uuid.UUID, skill_id: uuid.UUID) -> UserSkill | None: ...
    async def get_with_skill(self, user_id: uuid.UUID, skill_id: uuid.UUID) -> UserSkill | None: ...
    async def list_for_user(
        self, user_id: uuid.UUID, *, statuses: tuple[SkillStatus, ...] | None = None
    ) -> list[UserSkill]: ...
    async def rejected_skill_ids(self, user_id: uuid.UUID) -> set[uuid.UUID]: ...
    async def upsert_extracted(
        self, user_id: uuid.UUID, matches: list[tuple[uuid.UUID, int]]
    ) -> int: ...
    def add(self, entity: UserSkill) -> UserSkill: ...


class TaskDispatcher(Protocol):
    """How a service hands work to the queue.

    Abstracted for the same reason the repositories are: a unit test can substitute a recorder
    and assert that a task *would* have been enqueued, with no Redis running and no Celery
    imported. Without this, every test of the upload path would need a live broker.
    """

    def enqueue_resume_parse(self, resume_id: uuid.UUID) -> None: ...
    def enqueue_job_embedding(self, job_id: uuid.UUID) -> None: ...
