"""Initial schema: pgvector extension and users table

Revision ID: 0001_initial_users
Revises:
Create Date: 2026-08-11

Hand-written rather than autogenerated. Autogenerate does not know about the pgvector
extension, and the CHECK constraint and enum type need explicit ordering.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_users"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector is enabled in the very first migration rather than by a container init script,
    # so the extension exists identically on a laptop, in CI, and on Neon. Anything that lives
    # only in docker-compose is a step someone has to remember in production.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # The enum type is created explicitly, then referenced with `create_type=False`.
    # Without that flag SQLAlchemy emits its own CREATE TYPE while building the table, which
    # collides with the one above and fails with DuplicateObjectError. Creating it separately
    # is still worth doing: later migrations that add another table using this enum must not
    # try to create the type a second time.
    user_role = postgresql.ENUM("job_seeker", "recruiter", name="user_role", create_type=False)
    user_role.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("role", user_role, server_default="job_seeker", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name="ck_users_email_is_lowercase"),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
    # The vector extension is intentionally NOT dropped. Other objects may depend on it, and
    # dropping an extension is not something a schema rollback should do silently.
